export const FETCH_NOTIFICATION_KEYWORD = 'FETCH_NOTIFICATION_KEYWORD'
export const RESET_NOTIFICATION_KEYWORD = 'RESET_NOTIFICATION_KEYWORD'

export const NOTIFICATION_KEYWORD_OPEN = 'NOTIFICATION_KEYWORD_OPEN'
export const NOTIFICATION_KEYWORD_CLOSE = 'NOTIFICATION_KEYWORD_CLOSE'

export const NOTIFICATION_KEYWORD_VISIBLE = 'NOTIFICATION_KEYWORD_VISIBLE'
export const NOTIFICATION_KEYWORD_LOADING = 'NOTIFICATION_KEYWORD_LOADING'

export const CACHE_KEYWORDS = 'CACHE_KEYWORDS'
export const CACHE_REMOVE = 'CACHE_KEYWORDS'