export const MEETING_FETCHING = 'MEETING_FETCHING'
export const MEETING_FETCH_SUCESS = 'MEETING_FETCH_SUCESS'
export const MEETING_FETCH_ERROR = 'MEETING_FETCH_ERROR'
export const MEETING_FETCH_INSTANT = 'MEETING_FETCH_INSTANT'
export const MEETING_FETCH_CREATE_INSTANT = 'MEETING_FETCH_CREATE_INSTANT'
export const MEETING_FETCH_CREATE_INSTANT_AND_JOIN =
	'MEETING_FETCH_CREATE_INSTANT_AND_JOIN'
export const MEETING_ADD_INSTANT = 'MEETING_ADD_INSTANT'
