export const AUTH_FETCHING = 'AUTH_FETCHING'
export const AUTH_FETCH_SUCESS = 'AUTH_FETCH_LOGIN_SUCESS'
export const AUTH_FETCH_ERROR = 'FETCH_AUTH_ERROR'
export const AUTH_FETCH_GOOGLE_LOGIN = 'AUTH_FETCH_GOOGLE_LOGIN'
export const AUTH_FETCH_GOOGLE_LOGIN_VERIFY = 'AUTH_FETCH_GOOGLE_LOGIN_VERIFY'
export const AUTH_FETCH_EMAIL_LOGIN = 'AUTH_FETCH_LOGIN'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGGED = 'AUTH_LOGGED'
