import { Providers } from '@/redux/providers';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import Theme from '@/Theme/Theme';

import Footer from '@/components/Footer';
import '@livekit/components-styles';
import '@livekit/components-styles/prefabs';
import '@/scss/style.scss';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Theme> 
          <Providers>{children}</Providers>
        </Theme>
        <ToastContainer />
      </body>
    </html>
  );
}
