import Providers from '@/redux/providers';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import Theme from '@/Theme/Theme';

import Footer from '@/components/Footer';
import '@livekit/components-styles';
import '@livekit/components-styles/prefabs';
import 'react-toastify/dist/ReactToastify.css';
import '@/scss/style.scss';
import { ToastContainer } from 'react-toastify';
import AuthProvider from '@/container/AuthProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning={true}>
      <body>
        <Providers>
          <Theme>
            <AuthProvider>{children}</AuthProvider>
            <ToastContainer />
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
