export const KEYWORD_FETCHING = 'KEYWORD_FETCHING'
export const KEYWORD_RESET = 'KEYWORD_RESET '
export const KEYWORD_CONNECT_SOCKET = 'KEYWORD_CONNECT_SOCKET'
export const KEYWORD_DISCONNECT_SOCKET = 'KEYWORD_DISCONNECT_SOCKET'

export const KEYWORD_START_RECORD = 'KEYWORD_START_RECORD'
export const KEYWORD_END_RECORD = 'KEYWORD_END_RECORD'
export const KEYWORD_FETCHING_ERROR = 'KEYWORD_FETCHING_ERROR'

export const KEYWORD_SEND_TO_SOCKET = 'KEYWORD_SEND_TO_SOCKET'


export const POST_KEYWORD = 'POST_KEYWORD'
export const RESET_KETWORD = 'RESET_KETWORD'
export const DELETE_KEYWORD = 'DELETE_KEYWORD'