export const USER_FETCH_SUCESS = 'USER_FETCH_SUCESS'
export const USER_FETCH_ERROR = 'USER_FETCH_ERROR'
export const USER_FETCH_ME = 'USER_FETCH_ME'
export const USER_FETCH_UPDATE_ME = 'USER_FETCH_UPDATE_ME'

export const USER_SET_ME = 'USER_SET_ME'
